### ISSUE TITLE
website: Relative links in slides don't work on website

### ISSUE THREAD

**Issue by erin-le** [gem5bootcamp/2024#86]
Relative links (e.g. to materials) that work when viewing the slides in Codespaces don't work on the website. A fix could be to change the relative links to links to the GitHub repo. If this is done, I think this change should only be made to the slides for the website, as it is convenient to be able to jump to the materials when viewing the slides in Codespaces/locally. 

We could also make sure that the relative links include the full paths in the visible text.

**Comment by powerjg** [comment]
@nkrim Do you think you could take a look at this? I think we may need to extend marp with a plugin to get these links.

**Comment by nkrim** [comment]
Yeah I can take a look. I agree it's likely we would need to extend marp

**Comment by nkrim** [comment]
In the meantime, I think I can do a quick temporary fix to get it working with just the website (will not fix PDFs)
